import './global.css'
import Navbar from './components/Navbar.js'

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className='bg-lime-100'>
        <Navbar />
        {children}
      </body>
    </html>
  )
}